[package]
name = "backend"
version = "0.1.0"
edition = "2021"

[dependencies]
rodio = "0.19.0"
hound = "3.4.0"
actix-web = "4.0"
actix-cors = "0.7.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0.0"
